from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app.config import CONFIG
from app.gestures.training import export_runtime_model_bundle, train_svm_from_validated_dataset


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Train a baseline SVM candidate from a validated dataset artifact."
    )
    parser.add_argument(
        "--input-dataset",
        type=Path,
        default=CONFIG.paths.data_dir / "datasets" / "validated_dataset.json",
        help="Path to the validated dataset artifact generated by tools/validate_recordings.py",
    )
    parser.add_argument(
        "--output-model",
        type=Path,
        default=CONFIG.paths.data_dir / "datasets" / "svm_candidate.joblib",
        help="Path for the trained candidate artifact. This is not yet the runtime-approved export path.",
    )
    parser.add_argument(
        "--output-report",
        type=Path,
        default=CONFIG.paths.data_dir / "datasets" / "training_report.json",
        help="Path for the training summary report.",
    )
    parser.add_argument(
        "--export-runtime-model",
        type=Path,
        default=None,
        help="Optional runtime-approved bundle path, e.g. models/gesture_svm.joblib",
    )
    parser.add_argument(
        "--runtime-min-confidence",
        type=float,
        default=0.70,
        help="Minimum ML confidence to embed in the exported runtime bundle.",
    )
    return parser


def main() -> None:
    args = build_arg_parser().parse_args()
    result = train_svm_from_validated_dataset(
        args.input_dataset,
        output_model_path=args.output_model,
        output_report_path=args.output_report,
    )
    print(f"[Training] Labels: {', '.join(result.labels)}")
    print(f"[Training] Train samples: {result.sample_counts_by_split['train']}")
    print(f"[Training] Validation samples: {result.sample_counts_by_split['validation']}")
    print(f"[Training] Test samples: {result.sample_counts_by_split['test']}")
    print(
        f"[Training] Validation accuracy={result.metrics['validation'].accuracy:.3f} "
        f"macro_f1={result.metrics['validation'].macro_f1:.3f}"
    )
    print(
        f"[Training] Test accuracy={result.metrics['test'].accuracy:.3f} "
        f"macro_f1={result.metrics['test'].macro_f1:.3f}"
    )
    print(f"[Training] Model selection: {result.model_selection_status}")
    if result.best_params:
        print(f"[Training] Best params: {result.best_params}")
    if result.cv_strategy is not None and result.cv_best_score is not None:
        print(
            f"[Training] CV {result.cv_strategy} n_splits={result.cv_n_splits} "
            f"best_{'macro_f1'}={result.cv_best_score:.3f}"
        )
    print(f"[Training] Candidate artifact saved to {result.output_model_path}")
    print(f"[Training] Report saved to {result.output_report_path}")
    if args.export_runtime_model is not None:
        export = export_runtime_model_bundle(
            result.output_model_path,
            output_model_path=args.export_runtime_model,
            min_confidence=args.runtime_min_confidence,
            training_report_path=result.output_report_path,
        )
        print(
            f"[Training] Runtime bundle saved to {export.output_model_path} "
            f"(min_conf={export.min_confidence:.2f})"
        )


if __name__ == "__main__":
    main()
